### ISSUE TITLE
Fully flexible overrides per palette in the setup function

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/astrotheme#1]
The `palette` and `highlight` overrides need to be fully extendable on a per-palette basis. Ideally with the option for table override for simple extensions and also a `function` override format that gets passed in the palette and highlight groups for full extension with arbitrary lua. Also just to note it needs to be "per palette" so that you can extend specific palettes

**Comment by A-Lamia** [comment]
- [x] Overriding b796c0cd2edc729cc5cf6bb7a3bfa5cf7c69eaa9
- [ ] Modifying / Extending
