### ISSUE TITLE
Golang syntax highlighting isn't as good as other languages

### ISSUE THREAD

**Issue by AthirsonSilva** [AstroNvim/astrotheme#107]
### Is your feature related to a problem?

I migrated from VSCode today and, currently, everything is going smoothly, but one thing that is really bothering me is how the default theme doesn't show the "complete" syntax highlighting for Golang, and Golang only, i tested with Java, Lua, HTML and TypeScript and the syntax highlighting worked well with every single one. 

### Describe the new feature

Basically, it would be cool to make the syntax highlighting integrate better on Go, here goes a comparation between how the syntax highlighting works with Golang and TypeScript, and how much better it works for TypeScript.

![Screenshot from 2024-02-02 19-57-03](https://github.com/AstroNvim/astrotheme/assets/84593887/3dadd7e2-57f9-4522-8084-95dee42527ff)
![Screenshot from 2024-02-02 19-51-57](https://github.com/AstroNvim/astrotheme/assets/84593887/36fde3de-08d6-44d7-8ae5-46c98b55b2e4)

### Additional context

For additional context, i have the Golang LSP installed on my setup.

**Comment by mehalter** [comment]
https://github.com/golang/vscode-go/issues/2286

Looks like semantic tokens are disabled by default. It will be up to the treesitter parser or the language server to provide semantic tokens for them to be highlighted nicely. Syntax is controlled in a general level and not necessarily language specific

**Comment by mehalter** [comment]
You probably just need to configure gopls to enable semantic tokens in the settings to get better highlighting

**Comment by AthirsonSilva** [comment]
Oh, then i will take a look at it, many thanks!

**Comment by AthirsonSilva** [comment]
I don't know if reopening this issue or making a new post on the Discord would be the correct way, but i tried configuring gopls to enable semantic tokens and it didn't work, here goes my init.lua file:

```lua
return {
  opts = {
    clipboard = "unnamedplus",
    setup = {
      gopls = function(_, opts)
        require("lazyvim.util").on_attach(function(client, bufnr)
          if client.name == "gopls" then
            client.server_capabilities.semanticTokens = {
              full = true,
              legend = {
                tokenTypes = {
                  "namespace",
                  "type",
                  "class",
                  "enum",
                  "interface",
                  "struct",
                  "typeParameter",
                  "parameter",
                  "variable",
                  "property",
                  "enumMember",
                  "event",
                  "function",
                  "method",
                  "macro",
                  "keyword",
                  "modifier",
                  "comment",
                  "string",
                  "number",
                  "regexp",
                  "operator",
                  "decorator",
                },
                tokenModifiers = {
                  "declaration",
                  "definition",
                  "readonly",
                  "static",
                  "deprecated",
                  "abstract",
                  "async",
                  "modification",
                  "documentation",
                  "defaultLibrary",
                },
              },
            }
          end
        end)
        opts.settings = {
          gopls = {
            semanticTokens = true,
          },
        }
      end,
    },
  },
  highlights = {
    init = {},
  },
  plugins = {
    "gbprod/cutlass.nvim",
    "AstroNvim/astrocommunity",
    { import = "astrocommunity.motion.mini-move" },
    { import = "astrocommunity.project.nvim-spectre" },
    { import = "astrocommunity.project.projectmgr-nvim" },
  },
  mappings = {
    -- first key is the mode
    n = {
      -- second key is the lefthand side of the map
      -- mappings seen under group name "Buffer"
      ["<leader>bn"] = { "<cmd>tabnew<cr>", desc = "New tab" },
      ["<leader>bD"] = {
        function()
          require("astronvim.utils.status").heirline.buffer_picker(
            function(bufnr) require("astronvim.utils.buffer").close(bufnr) end
          )
        end,
        desc = "Pick to close",
      },
      -- tables with the `name` key will be registered with which-key if it's installed
      -- this is useful for naming menus
      ["<leader>b"] = { name = "Buffers" },
      -- quick save
      ["<C-s>"] = { ":w!<cr>", desc = "Save File" }, -- change description but the same command
      ["d"] = { '"_d', desc = "Deletes current line without copying the contents" },
      -- ["<Del>"] = { '"_d', desc = "Delete visual selection without saving to clipboard" },
    },
    v = {
      -- setting a mapping to false will disable it
      -- ["<esc>"] = false,
      ["<Del>"] = { '"_d', desc = "Delete visual selection without saving to clipboard" },
    },
  },
}
```

I found this configuration on this Reddit post: https://www.reddit.com/r/neovim/comments/11xekjx/how_to_make_semantic_token_highlighting_work_with/

One interesting thing is that in the post it was metioned that semantic tokens should be built in in neovim now, but i am already using a recent version of neovim right now:

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

**Comment by mehalter** [comment]
This is incorrect @AthirsonSilva

1. this is using utilities in `LazyVim` which aren't available in AstroNvim
2. Semantic tokens are default in 0.9+ so you don't need to enable the capability. 

All you need to do is create a file `user/lsp/config/gopls.lua` and give it the content:

```lua
return {
  settings = {
    gopls = {
      semanticTokens = true,
    },
  },
}
```

**Comment by mehalter** [comment]
![2024-02-03_10:05:21_screenshot](https://github.com/AstroNvim/astrotheme/assets/1591837/8c939ac2-fe94-49d8-b9aa-b1ee41d7adf8)


here is an example with just that added in a base AstroNvim install.
