### ISSUE TITLE
Floats blend with main window (no borders or different bg color)

### ISSUE THREAD

**Issue by lfilho** [AstroNvim/astrotheme#124]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14

### Terminal/GUI

iterm2

### Describe the bug

See screenshots below featuring Mason and Telescope: the floating windows blend with the theme's dark background, so it's not too nice to look at, hard to say where one begins and the other ends.

It would be nice to either change backgrounds colors (make the float a different bg color or maybe dim the underlying windows. The issue is worse with Mason because there's no border at all (see screenshots).

### Steps to Reproduce

1. Open a float (Telescope or Mason, for example)
2. See it the background is the same and that's is hard to tell it apart from the underlying windows

### Expected behavior

I'd like to clearly see it's a floating window

### Screenshots

![CleanShot 2024-05-07 at 17 37 35](https://github.com/AstroNvim/astrotheme/assets/282756/f927f469-8890-4b71-b1eb-f3debc0396f6)

![CleanShot 2024-05-07 at 17 41 47](https://github.com/AstroNvim/astrotheme/assets/282756/6b0d69da-02d4-45f2-aa02-1c404c090780)

### Additional Context

Thank you!

**Comment by mehalter** [comment]
have you customized the AstroTheme configuration at all? The default AstroNvim setup dims pretty heavily

![2024-05-07_20:47:55_screenshot](https://github.com/AstroNvim/astrotheme/assets/1591837/156678e7-0335-4536-a378-707a7797af31)

**Comment by lfilho** [comment]
Hey @mehalter thanks for replying. I have not customized astro theme's or highlights. But notice how even on your screenshot we can't tell where Mason's window starts or ends. It seems it's dimming the fg but not the bg?

The autocompletion with `<C-Space>` is a bit better because it at least has a border:

![CleanShot 2024-05-07 at 18 12 32](https://github.com/AstroNvim/astrotheme/assets/282756/b639dd9a-6b54-404b-88de-7e98465d4ca1)

But the one with `<C-n>` doesn't:
![CleanShot 2024-05-07 at 18 13 29](https://github.com/AstroNvim/astrotheme/assets/282756/dc514827-8880-4b0b-84f5-64e80c5c9cde)

Feels like all those floats should behave the same and have a clear indication they're a float/modal on top of something else

**Comment by mehalter** [comment]
these plugins all have different methods of things. the completion menus are Pmenus and not buffers. Buffers are darkened when they are not active and active buffers are lightened. That is why the mason window is lightened and the background is darkened. Mason does not have a border by default and I'm not sure if it's configurable. It's unrelated to the highlights in this case. The `<C-n>` menu is the default completion also not something with a border. We go out of our way to add a border to `cmp` because it makes it easier

**Comment by mehalter** [comment]
because active windows are lightened, floating menus are naturally darkened to create a strong contrast and clear semantic separation. I don't think we want to change these default highlights at all because of this

**Comment by mehalter** [comment]
If you play around with it and come up with some better defaults feel free to open a PR with suggestions

**Comment by lfilho** [comment]
Thanks @mehalter 

> these plugins all have different methods of things.
Yeah, I get that. So are you saying that for Astro's theme there's not appetite to provide that more consistent experience/UX across those plugins? I thought that for those in particular we would since they're an integral part of AstroNvim itself.

> to create a strong contrast and clear semantic separation
That's exactly what i want! My point here is that it is not happening. i.e. the contrast is not high enough, it is barely visible! You have to squint to (maybe) be able to tell where the floats start and end

> If you play around with it and come up with some better defaults feel free to open a PR with suggestions
will do. As a matter of fact i was trying it as this thread developed, and I ran into a hiccup. The v4 template suggests using "astrotheme" as key to customize highlights: https://github.com/AstroNvim/template/blob/main/lua/plugins/astroui.lua#L20 but that didn't work for me. but if I change it to "astrodark" then it works. Even when i do ":colors astrotheme" and the immediately i call ":colors", the result is "astrodark", not "astrotheme", so that might be preventing the customizations to work like the template suggests.

Will follow up here when i have something to show/propose. Thanks again

---

i have also identified

**Comment by lfilho** [comment]
Thoughts?
Played with it for a bit. Here's how a completion and Mason looks like. Thoughts?

![CleanShot 2024-05-07 at 19 46 41](https://github.com/AstroNvim/astrotheme/assets/282756/68dec910-255e-423a-b5f7-abb8bba4bc9e)

![CleanShot 2024-05-07 at 19 47 16](https://github.com/AstroNvim/astrotheme/assets/282756/aa8fa471-2731-4e5a-b824-3458412c12d9)

**Comment by mehalter** [comment]
This doesn't fit with the vibe and decreases contrast within the window. Also it doesn't seem to really change the contrast all that much between the foreground and background windows. It seems to be more warm toned and brown rather than the cool toned and blueish part of the theme

**Comment by lfilho** [comment]
Welp, I tried :D 

I'll leave the config here if people in the future is interested:

```lua
      astrodark = { -- a table of overrides/changes when applying the astrotheme theme
        FloatBorder = { fg = "#cccccc" },
        NormalFloat = { bg = "#333333" },
        PMenu = { bg = "#333333" },
        PMenuSel = { bg = "#999999", fg = "#000000" },
        WinSeparator = { fg = "#666666" },
      },
```

**Comment by A-Lamia** [comment]
I'd like to note, there is no wrong or right answer to what each individual feels is better for them, that's why a lot of time was spent to make things really easy to modify, a lot of time is spent on my side with real tooling to make sure as much parts of AstroThemes as possible is with scientific contrast levels. Thanks for your input though.

As a side note, you can also add borders in the AstroTheme config it's a bool toggle, if you go through the documentation for AstroTheme there is a lot of settings for you to use :).

**Comment by lfilho** [comment]
Hey @A-Lamia totally in agreement! And I thank for your efforts! That's why I'm trying the theme out to begin with! 😊 

As for the bool toggle for borders, not sure what you meant: it is true by default and i didn't change it... 

Here's the config I had to do to actually enable borders to Lazy and Mason (after reading their documentation, ideally and integrated theme like this would abstract this away):

on `lazy_setup`:

```lua
require("lazy").setup({
  {
    "AstroNvim/AstroNvim",
    [...]
    ui = { backdrop = 100, border = "rounded" },
    [...]
} --[[@as LazyConfig]])
```

anywhere in your plugins/:

```lua
return {
  {
    "williamboman/mason.nvim",
    opts = {
      ui = {
        border = "rounded",
      },
    },
  },
}
```

So maybe by setting the border = true in the theme, the theme should go ahead and do what the above for Lazy and Mason too? 

Here's how Lazy looks now:
![CleanShot 2024-05-07 at 21 04 59](https://github.com/AstroNvim/astrotheme/assets/282756/03a77bb5-3fad-4d2d-84ef-d0e9eb99f0ba)


and mason:
![CleanShot 2024-05-07 at 21 05 38](https://github.com/AstroNvim/astrotheme/assets/282756/4036e8b9-9ec1-4c69-90d1-97fc3836ee54)

I think even with just the borders (without my custom background), it would already be a big improvement. But again, as you mentioned, it's all a matter of preferences in the end ;)

Thanks again!

**Comment by A-Lamia** [comment]
That would be up to AstroNvim it self to abstract that out in to a global border toggle, we get in to really strange territory when themes are modifying plugin config settings. Potentially also overriding user preferences, Imagine you had put all that work just now to enable borders and a theme you downloaded disabled them, and now you need to fight with it for load order or visa versa. :)

**Comment by lfilho** [comment]
Yes, I agree it would have to be at the AstroNvim level, not the theme. The theme could then just customize colors, etc.

Regarding "people didn't like it overwriting there own settings", maybe an option wouldbe be to make it an opt-in config...
