### ISSUE TITLE
Improve php tag `<?php ... ?>` highlight

### ISSUE THREAD

**Issue by AlejandroSuero** [AstroNvim/astrotheme#143]
### Is your feature related to a problem?

The current state of the highlight in php `@punctuation.bracket.php` is linked to text highlight with `@punctuation.bracket`

![Screenshot 2024-09-15 at 05 18 32](https://github.com/user-attachments/assets/56725d82-b998-45cf-acc6-fd8611f56975)

### Describe the new feature

Isolate php from the rest of `@punctuation.bracket` because is kinda special.

**Comment by mehalter** [comment]
Closed with #144
