### ISSUE TITLE
DiffAdd and DiffDelete colors

### ISSUE THREAD

**Issue by machin3io** [AstroNvim/astrotheme#17]
Hi,

why is it that when writing git commit messages, or reviewing commits via telescope (in astronvim with astrothem), it shows both added and deleted lines equally blue? Is this intended or is something not working properly for me?

See https://imgur.com/a/NGH8FpU

To make the removed lines appear red and the added lines appear green i had to change colors for the Identifier and Special highlight groups. But I don't understand why.

See https://imgur.com/a/q8ChjKW

Setting DiffAdd and DiffDelete colors seemed to have no effect.

I'd appreciate any input on this. 

Also, just wanted to let you know, very nice work on Astronvim and the Astrotheme. I've only recently switched to nvim from vim, and was running a custom setup for a few months, but yours is so much better out of the box. I'm very impressed with the LSP integration, and and the fluidity and responsive of it all. So many good choices were made for this. Thank you.

**Comment by A-Lamia** [comment]
@machin3io 
Hey thanks for reporting, now i see the table has turned and it's time for me to help you LOL, you have given me assistance before on some of your blender products :)

I'll check now what's happening with the colors.

(Still waiting for hyper cursor)

**Comment by A-Lamia** [comment]
So i do see there is an issue, when there shouldn't be but interestingly they are both blue for you and not one red one blue, can you please give me some details

* OS
* nvim version
* AstroNvim Version
* last time you updated your packages

**Comment by A-Lamia** [comment]
@machin3io thank you! after investigation it seems that Telescope does not us `Diff*` for the commit and the colors are correct, i do however understand that having blue for deletion and red for add is horrible for UX, so i will do some looking into where telescope is pulling these colors from and have them changed to be green and red :)

**Comment by mehalter** [comment]
```
diffAdded
diffRemoved
diffChanged
diffOldFile
diffNewFile
diffFile
diffLine
diffIndexLine
```

After investigation we found the missing highlight groups. We will be putting together a PR to fix this :)

**Comment by A-Lamia** [comment]
All good now if you find any other issues or have suggestions please let us know :D
