### ISSUE TITLE
Add Heirline mode highlight groups to AstroNvim highlight module

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/astrotheme#2]
Along with the `HighlightURL` highlight group, AstroNvim also uses some custom Heirline highlight groups we should add. The default definition for the `astrodark` colorscheme are found here:

https://github.com/AstroNvim/AstroNvim/blob/4f4269d174d85df8b278a6e09d05daeef840df4a/lua/configs/heirline.lua#L24-L37

**Comment by A-Lamia** [comment]
Closing with: fce1e3b526039cc4a6b091c5395204479d410140
