### ISSUE TITLE
Colorscheme issues after running <leader>pa (Update Plugins and Mason)

### ISSUE THREAD

**Issue by whoop-t** [AstroNvim/astrotheme#28]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS Ventura Version 13.2.1

### Terminal/GUI

iterm2 and kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

The default Astrotheme seems to have changed once I ran leaderpa to update. Screenshots provided below.
The colorscheme was correct until I ran leaderpa
Tested on 2 separate computers(work/personal), both same issues
Tested on iterm2 and kitty, both same issues

I tried removing Astronvim with:
```bash
rm -rf ~/.config/nvim
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim
```
Then just install base Astronvim, installing tsserver lsp and javascript/typescript treesitters. Same issue.

Updated to Neovim v0.9.0(was previously v0.8.3), same issues

_Note: Ive only tested with JS/TS files_

### Steps to Reproduce

1. Install Astronvim
2. Open a JS/TS file, install treesitter
3. Notice colors are not same as `astrodark` gettings cyan methods and no bracket colorization, etc.

### Expected behavior

Default astrodark theme

### Screenshots

Before:
![good](https://user-images.githubusercontent.com/52976607/232324051-f205a7fe-ea05-4e30-affd-b626827d8a08.png)

After:
![Screenshot 2023-04-15 at 10 09 51 PM](https://user-images.githubusercontent.com/52976607/232324067-7d2bca75-3220-451b-8646-88beca602a39.png)

Another screenshot with issue:
![Screenshot 2023-04-15 at 9 59 04 PM](https://user-images.githubusercontent.com/52976607/232324101-d784184e-b610-4443-8d8d-f6f2329b3942.png)

**Comment by mehalter** [comment]
@whoop-t there are a few things. 

1. I transferred this issue to the appropriate repo
2. we have made changes to the default colors in AstroTheme recently @A-Lamia can talk about those
3. The rainbow parentheses are probably coming from the plugin which AstroNvim no longer comes with. So you will need to install it yourself if you want it.

**Comment by A-Lamia** [comment]
So what are your actually issues other then the colors are different. 

I'll need to look in to the Cyan methods I'm not 100% with how it's decided but it should only be Cyan for TS/JS methods and all user methods should be blue.

**Comment by A-Lamia** [comment]
seems i did have methods though set to cyan ill fix that now, the intention was only for builtin functions to be cyan.

**Comment by A-Lamia** [comment]
Has this issue been resolved ?

**Comment by whoop-t** [comment]
I started using Tokyo night, haven't tested default theme in a while

You can close this
