### ISSUE TITLE
`folke/noice.nvim` cursor not rendering

### ISSUE THREAD

**Issue by Hacksore** [AstroNvim/astrotheme#32]
When using [noice.nvim](https://github.com/folke/noice.nvim) the cursor is not shown in either `astrolight` or `astrodark` but works fine in the other non-astro themes.

astrodark
![image](https://github.com/AstroNvim/astrotheme/assets/996134/01c03270-fa5e-4792-8d67-e71eaf8914d9)

astrolight
![image](https://github.com/AstroNvim/astrotheme/assets/996134/eb8346b6-5f47-4df0-ac71-d9dfdee56ce8)

slate
![image](https://github.com/AstroNvim/astrotheme/assets/996134/093aa065-87d8-498b-a56b-1f90754a5bd7)

**Comment by utkarshgupta137** [comment]
You can change the highlight of `NoiceCursor` as a workaround: https://github.com/utkarshgupta137/nvim-astro/blob/d44989e/highlights/astrotheme.lua#L6
