### ISSUE TITLE
Support better colors for `nvim-dap-ui`

### ISSUE THREAD

**Issue by Hacksore** [AstroNvim/astrotheme#35]
When using the [`nvim-dap-ui`](https://github.com/rcarriga/nvim-dap-ui) plugin it looks like the font color for the variables are not visible.

astrodark
![image](https://github.com/AstroNvim/astrotheme/assets/996134/cc28f1d4-71a6-49cd-83f8-50cf254e2d4a)

astrolight
![image](https://github.com/AstroNvim/astrotheme/assets/996134/07913c84-b504-4867-9420-cea12c4d78d6)

**Comment by A-Lamia** [comment]
thanks ill look in to this :)

**Comment by A-Lamia** [comment]
This has been fixed and will close automatically once merged.
Thanks for the report!
