### ISSUE TITLE
Contrast text in git diff

### ISSUE THREAD

**Issue by Hacksore** [AstroNvim/astrotheme#38]
If you `<leader>gd` then try to select something from the diff the text is not legible.

![image](https://github.com/AstroNvim/astrotheme/assets/996134/2d2e83e0-971b-4ebe-a73d-ec6075bc4802)

**Comment by Hacksore** [comment]
@A-Lamia or @mehalter what is the best way to provide debug information that is helpful to progress this issue?

**Comment by Hacksore** [comment]
Testing on `astrolight` similar issue as seen in the original post.
![image](https://github.com/AstroNvim/astrotheme/assets/996134/d7bbae7c-f329-4ee8-851e-ee97854f8705)

Using `slate` it's not quite as bad.
![image](https://github.com/AstroNvim/astrotheme/assets/996134/b1bff226-4c93-4263-a1f5-d68efa7c66e3)

So I was trying this to override the Visual highlights but no luck.
```lua
{
 "lewis6991/gitsigns.nvim",
 event = "user astrofile",
 config = function()
  require("gitsigns").setup({
   signs = {
    add = { text = "▎" },
    change = { text = "▎" },
    delete = { text = "▎" },
    topdelete = { text = "契" },
    changedelete = { text = "▎" },
    untracked = { text = "▎" },
   },
  })

  local ns = vim.api.nvim_get_namespaces()

  vim.api.nvim_set_hl(ns.gitsigns, "Visual", { fg = "#ffffff", bg = "#000000" })
 end,
}

```

**Comment by Hacksore** [comment]
Started a thread with gitsigns maintainer and his theme works well but there might not be a good way to solve this.

https://matrix.to/#/!wZXiOwCgfPiJjztzbF:gitter.im/$RrCTmlvoW9ZUqoGLNEhKahXvh1VlCUJ_YF8xCo1rU4I?via=matrix.org&via=gitter.im

**Comment by A-Lamia** [comment]
I've been playing around with this and there just doesn't seem to be anything i can do for visual selected as there is not an alternative, i can modify it a little to try get a little more contrast but that's about it.

**Comment by A-Lamia** [comment]
So after talking and some thoughts, this is out of the scope of what a theme should be doing, or what astro should be doing, this sort of logic should be handled by the user or plugin creators, thanks for reporting though, i will try to optimize the colors a bit.

**Comment by Hacksore** [comment]
Here is the workaround I have for now, thanks for looking into this nevertheless.


https://github.com/AstroNvim/astrotheme/assets/996134/f61c7e8b-dd91-4e4b-b782-59e810f54568

https://github.com/Hacksore/dotfiles/commit/5931064e3b5332224c3a8f12c7a9906e4ba94bc8
