### ISSUE TITLE
Normal and highlight colors swapped

### ISSUE THREAD

**Issue by cjauton** [AstroNvim/astrotheme#40]
Not sure if this is an issue or intensional, but I believe some of the colors for the terminal are flipped between their normal and bright counterparts. This is the neofetch color block output now:
<img width="207" alt="Screenshot 2023-06-19 at 4 08 03 PM" src="https://github.com/AstroNvim/astrotheme/assets/126740758/797a1422-3f17-4448-bcf0-66f7c2677366">
This is how I believe it should be:
<img width="200" alt="Screenshot 2023-06-20 at 12 11 20 PM" src="https://github.com/AstroNvim/astrotheme/assets/126740758/ef8379a1-e9da-41a8-86a1-a1ebe50f5b88">

**Comment by cjauton** [comment]
Also here is a side-by-side colortest output.
<img width="1147" alt="Screenshot 2023-06-20 at 12 31 17 PM" src="https://github.com/AstroNvim/astrotheme/assets/126740758/aaf3795e-4dff-452c-a828-79f4e623ea2f">

**Comment by cjauton** [comment]
I just noticed another thing. The terminal is not using the highlight colors.

**Comment by A-Lamia** [comment]
yes ill have a look at whats going on with this, thanks!

**Comment by mehalter** [comment]
This is resolved in the upcoming v2 release and is available on the current `main` branch. Will be on stable AstroNvim very soon :)
