### ISSUE TITLE
Is `crust` a bit too warm for this cool theme?

### ISSUE THREAD

**Issue by pkazmier** [AstroNvim/astrotheme#42]
I understand colors are subjective, but I'm curious if anyone else finds `crust` a bit too "warm" (red) for this relatively "cool" gray theme? In my opinion, it looks out of place in this otherwise beautiful default theme. `crust` is used as the background for Neo-Tree as seen in this screenshot:

<img width="1867" alt="image" src="https://github.com/AstroNvim/astrotheme/assets/747855/197886ed-3633-4170-b781-30a03a0344a2">

Interestingly, none of the screenshots for Astronvim or Astrodark seem to use this warm color for Neo-Tree either. If I measure the color in the official Astrodark screenshot, it is `#1B1F27`. So, I use that in my own configuration as seen in this screenshot, which matches the palette of the theme better:

<img width="1867" alt="image" src="https://github.com/AstroNvim/astrotheme/assets/747855/e85c5c9c-7e44-431d-a53b-bb447cac609e">

Would anyone be opposed if I submitted a PR with the change?

**Comment by A-Lamia** [comment]
I'm currently refactoring all these colors in a large update coming soon, this theme has some changes made too it, this being one of them :)

**Comment by pkazmier** [comment]
Yes, that is exciting. I quickly reviewed the PR and saw a lot of changes. I'm excited to see the final product. It does not, however, look like `M.crust` is changed. I think the current RGB value is just a bit too warm / red. Hopefully, you'll consider cooling it a bit. Thanks!

**Comment by A-Lamia** [comment]
@pkazmier i have not pushed a lot of changes ;D

**Comment by pkazmier** [comment]
Ah, understood! Let me know if you need help with a beta tester once you are further along. I'd be happy to assist.

**Comment by A-Lamia** [comment]
ill upload some changes soon. this is currently what it is looking like
![image](https://github.com/AstroNvim/astrotheme/assets/6450181/f167805a-84ad-4e88-aee0-4aa4ca783be8)
![image](https://github.com/AstroNvim/astrotheme/assets/6450181/f333a506-f8bc-4d91-a685-396d36de2378)
![image](https://github.com/AstroNvim/astrotheme/assets/6450181/76497b84-1130-4cf7-8ae8-b1687b0a0c10)

**Comment by mehalter** [comment]
This is resolved in the upcoming v2 release and is available on the current main branch. Will be on stable AstroNvim very soon :)
