### ISSUE TITLE
Value of italic_comments not respected

### ISSUE THREAD

**Issue by pkazmier** [AstroNvim/astrotheme#48]
The value of `italic_comments` is not respected in lua/astrotheme/lib/config.lua, nor is the value in a user configuration:

```lua
    opts = {
      style = {
        italic_comments = true,
      },
    },
```

**Comment by mehalter** [comment]
Are you using the latest version of AstroTheme or the latest stable release?

**Comment by pkazmier** [comment]
Ah, yes, should have been more clear. On the latest and greatest and testing out the new version you guys have been working on. It looks amazing and is now my new favorite color scheme (astrodark, still can't onboard with mars yet).

**Comment by A-Lamia** [comment]
should be ready to go now thanks for the report!
https://github.com/AstroNvim/astrotheme/pull/49

**Comment by pkazmier** [comment]
Thank you. It works now. Again, great job on this major refactoring.
