### ISSUE TITLE
Brackets not highlighted

### ISSUE THREAD

**Issue by wqk151** [AstroNvim/astrotheme#77]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu20.04

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.33.5
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

1. Brackets not highlighted.
2. The highlight color of the same variable is very light, is there a way to modify the background color? As shown in the figure below
![3](https://github.com/AstroNvim/AstroNvim/assets/18275602/ba4ba811-d02f-45a6-8569-6e218b380dcf)

### Steps to Reproduce

1.  Brackets not highlighted.
![1](https://github.com/AstroNvim/AstroNvim/assets/18275602/f0f40f90-97c8-4f5a-b310-31b317785c9e)

### Expected behavior

like this
![2](https://github.com/AstroNvim/AstroNvim/assets/18275602/b2f16b72-4c2f-4412-aba2-d877ef4b2afa)

**Comment by diegorodriguezv** [comment]
Hi. I'm new to astronvim but I'm experiencing the same problem. Is there a workaround?

**Comment by diegorodriguezv** [comment]
Hi again. I found a suboptimal workaround:

     :colorscheme astrolight
Both astrodark and astromars have the reported problem.

**Comment by diegorodriguezv** [comment]
I also discovered that when using astrodark or astromars there is an almost imperceptible change in the highlighted character background.
