### ISSUE TITLE
Current buffer highlight group?

### ISSUE THREAD

**Issue by karambaq** [AstroNvim/astrotheme#79]
How can I change style of current selected buffer in status line?

**Comment by A-Lamia** [comment]
could you elaborate on that for me, change what exactly ?

**Comment by karambaq** [comment]
Sorry, don't know how it's called, current file background tab in the bufferline

<img width="362" alt="image" src="https://github.com/AstroNvim/astrotheme/assets/14233969/92fa102e-82a4-44cf-97bc-d755f0e4b121">

**Comment by A-Lamia** [comment]
oh that is an astronvim question
